name: Progress Bar CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5

    # Runs a single command using the runners shell
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Update README.md
      run: node index.js > README.md

    - name: Get current date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
     
    # Runs a set of commands using the runners shell
    - name: Commit Change & Push
      run: |
        git config user.name 'Arthur G. Buhl'
        git config user.email 'arthurbuhl@users.noreply.github.com'
        git commit -am "chore: update readme ${{ env.NOW }} [skip ci]"
        git push
